# Generated by Django 5.1.4 on 2024-12-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
