# Generated by Django 5.1.4 on 2024-12-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_category_owner_remove_task_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
