# Generated by Django 5.1.4 on 2024-12-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_priority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
